[[Capstone]]
arch = "aarch64"
git-tree-sha1 = "c5782c1d2e847459c5f931ce12fb1876015c37b7"
os = "macos"

    [[Capstone.download]]
    sha256 = "828ccc9e0f2d9854cdc88c4df46abd5678cc0f13ea9ea4f1d4dc1bb0519e963c"
    url = "https://github.com/JuliaBinaryWrappers/Capstone_jll.jl/releases/download/Capstone-v4.0.3+0/Capstone.v4.0.3.aarch64-apple-darwin.tar.gz"
[[Capstone]]
arch = "aarch64"
git-tree-sha1 = "3a29325228695168155a31053c80e4cad2ab9ca6"
libc = "glibc"
os = "linux"

    [[Capstone.download]]
    sha256 = "77af55056e13a4e3bb5e5375bdf6b80feba0e05eaa0ae0cc58f0cd09163edb13"
    url = "https://github.com/JuliaBinaryWrappers/Capstone_jll.jl/releases/download/Capstone-v4.0.3+0/Capstone.v4.0.3.aarch64-linux-gnu.tar.gz"
[[Capstone]]
arch = "aarch64"
git-tree-sha1 = "24d4124ca83dd120323133146a7f260731d92217"
libc = "musl"
os = "linux"

    [[Capstone.download]]
    sha256 = "e9ca0a81b02d9dfbfba20c0c5786b08978e3082c7b6bbf05ffaf51f8a3763d16"
    url = "https://github.com/JuliaBinaryWrappers/Capstone_jll.jl/releases/download/Capstone-v4.0.3+0/Capstone.v4.0.3.aarch64-linux-musl.tar.gz"
[[Capstone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ca7f4c2c43caa717fbfbcd7cc16026eb8b61434a"
libc = "glibc"
os = "linux"

    [[Capstone.download]]
    sha256 = "aabe36d6ef9487690bfb0dd28c8e687ad48f5a4ee21f840a7fffb8bb18c0c3a1"
    url = "https://github.com/JuliaBinaryWrappers/Capstone_jll.jl/releases/download/Capstone-v4.0.3+0/Capstone.v4.0.3.armv6l-linux-gnueabihf.tar.gz"
[[Capstone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cd74746f68c80770fc0f29b4ce7447cf5acbb10a"
libc = "musl"
os = "linux"

    [[Capstone.download]]
    sha256 = "0beb2a7de6df099a909d635e1f936f12c1b8854d3c918b7c4d4e4e011576df98"
    url = "https://github.com/JuliaBinaryWrappers/Capstone_jll.jl/releases/download/Capstone-v4.0.3+0/Capstone.v4.0.3.armv6l-linux-musleabihf.tar.gz"
[[Capstone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fe8d1d4a50bc13ce8b3d23ff4d53aad065f0eec2"
libc = "glibc"
os = "linux"

    [[Capstone.download]]
    sha256 = "6b70752ed3ed11cf9bad8ed9df09bbae00f89910c7631e946577b84574bb0589"
    url = "https://github.com/JuliaBinaryWrappers/Capstone_jll.jl/releases/download/Capstone-v4.0.3+0/Capstone.v4.0.3.armv7l-linux-gnueabihf.tar.gz"
[[Capstone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e30dcc61ba0fce81e17fa5f8d2d1ab114f501f9a"
libc = "musl"
os = "linux"

    [[Capstone.download]]
    sha256 = "58fecaa13cb72b37688c83b5d8f358b57e7eaa61d2905a35b325f706d22ef4cb"
    url = "https://github.com/JuliaBinaryWrappers/Capstone_jll.jl/releases/download/Capstone-v4.0.3+0/Capstone.v4.0.3.armv7l-linux-musleabihf.tar.gz"
[[Capstone]]
arch = "i686"
git-tree-sha1 = "efa87b95446dc50eb48e1bf15ece0684e0eb63f8"
libc = "glibc"
os = "linux"

    [[Capstone.download]]
    sha256 = "2b507242e12b704129ac7ecb2a308c8b7fa09fce99fafc2565be8d9f7a9e8962"
    url = "https://github.com/JuliaBinaryWrappers/Capstone_jll.jl/releases/download/Capstone-v4.0.3+0/Capstone.v4.0.3.i686-linux-gnu.tar.gz"
[[Capstone]]
arch = "i686"
git-tree-sha1 = "6bb3ae6545fd70c8cf871ad43a0b820dd4f369e7"
libc = "musl"
os = "linux"

    [[Capstone.download]]
    sha256 = "b2436696eb0c25199e59146985a86260c39eb69686be999e8052b449f5b4d016"
    url = "https://github.com/JuliaBinaryWrappers/Capstone_jll.jl/releases/download/Capstone-v4.0.3+0/Capstone.v4.0.3.i686-linux-musl.tar.gz"
[[Capstone]]
arch = "i686"
git-tree-sha1 = "977074900fc7ac61ba1cd894faf5770fe6093554"
os = "windows"

    [[Capstone.download]]
    sha256 = "83e65171d5306adea4798dcb9b1ea6126592703ef14102e55dabf6d9797e6b26"
    url = "https://github.com/JuliaBinaryWrappers/Capstone_jll.jl/releases/download/Capstone-v4.0.3+0/Capstone.v4.0.3.i686-w64-mingw32.tar.gz"
[[Capstone]]
arch = "powerpc64le"
git-tree-sha1 = "f235fc889a267f9157ef81cb992e508951e36128"
libc = "glibc"
os = "linux"

    [[Capstone.download]]
    sha256 = "d531c51443a77fafed16f9eb6bb2229c9169a18a0af05aa3aed76e43a349fd90"
    url = "https://github.com/JuliaBinaryWrappers/Capstone_jll.jl/releases/download/Capstone-v4.0.3+0/Capstone.v4.0.3.powerpc64le-linux-gnu.tar.gz"
[[Capstone]]
arch = "x86_64"
git-tree-sha1 = "e8ff199caf59464450dec680e4cf20fb2e509156"
os = "macos"

    [[Capstone.download]]
    sha256 = "1739a2dda0744a47888afac4c6909aa6823783ff093061e393442a0a7844c884"
    url = "https://github.com/JuliaBinaryWrappers/Capstone_jll.jl/releases/download/Capstone-v4.0.3+0/Capstone.v4.0.3.x86_64-apple-darwin.tar.gz"
[[Capstone]]
arch = "x86_64"
git-tree-sha1 = "3efe0b355fea84da8a9269cb2929e6e000419c6f"
libc = "glibc"
os = "linux"

    [[Capstone.download]]
    sha256 = "7716aae35af01c40da18479448ea5c45d108d1d15ab6abdfb96557d9194e6bbe"
    url = "https://github.com/JuliaBinaryWrappers/Capstone_jll.jl/releases/download/Capstone-v4.0.3+0/Capstone.v4.0.3.x86_64-linux-gnu.tar.gz"
[[Capstone]]
arch = "x86_64"
git-tree-sha1 = "dbb5854e2e0de23a132c33724a39c32676b35bb3"
libc = "musl"
os = "linux"

    [[Capstone.download]]
    sha256 = "03b99839d9f0247e3cbe585fa8bb6c2f2a16e6604aeb92000cb90b95ba26b406"
    url = "https://github.com/JuliaBinaryWrappers/Capstone_jll.jl/releases/download/Capstone-v4.0.3+0/Capstone.v4.0.3.x86_64-linux-musl.tar.gz"
[[Capstone]]
arch = "x86_64"
git-tree-sha1 = "b03e533e7f4e9c2d16cbe458cb9a85ad5667ea5b"
os = "freebsd"

    [[Capstone.download]]
    sha256 = "44e9dfefaa012a55f9c5649cd766164f65fa0a04e9698bf40162c116122f772c"
    url = "https://github.com/JuliaBinaryWrappers/Capstone_jll.jl/releases/download/Capstone-v4.0.3+0/Capstone.v4.0.3.x86_64-unknown-freebsd.tar.gz"
[[Capstone]]
arch = "x86_64"
git-tree-sha1 = "ef8e10bb21642d5392117c3a3b254505743d25d4"
os = "windows"

    [[Capstone.download]]
    sha256 = "17e700ed6c6f55c46d67611495373c2f263ceef850255d2b5c5ed3f7a67546ca"
    url = "https://github.com/JuliaBinaryWrappers/Capstone_jll.jl/releases/download/Capstone-v4.0.3+0/Capstone.v4.0.3.x86_64-w64-mingw32.tar.gz"
